services:

  postgres:
    container_name: to-do-app-postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password2
      POSTGRES_USER: postgres
      POSTGRES_DB: to-do-app-db
    ports:
      - "5432:5432"
    volumes:
      - to-do-app-data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.1
    container_name: to-do-app-redis
    ports:
      - "9988:6379"
    restart: always

  backend:
    container_name: to-do-app-be
    image: to-do-app:latest
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/to-do-app-db"
      SPRING_DATE_REDIS_HOST: "redis"
      SPRING_PROFILES_ACTIVE: "local"
    ports:
      - "8080:8080"
    profiles:
      - backend

volumes:
  to-do-app-data:
    driver: local