services:

  postgres:
    container_name: to-do-app-postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password2
      POSTGRES_USER: postgres
      POSTGRES_DB: to-do-app-db
    ports:
      - "5432:5432"
    volumes:
      - to-do-app-data:/var/lib/postgresql/data

volumes:
  to-do-app-data:
    driver: local