name: ToDo App Build

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  pull-requests: write
  checks: write

jobs:
  build:
    name: Build and Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Compile
        run: ./gradlew assemble --no-daemon

      - name: Run unit tests
        run: ./gradlew test --no-daemon

      - name: Run integration tests
        run: ./gradlew integrationTest -x test --no-daemon

      - name: Code coverage
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Code coverage report decoration
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 90
          min-coverage-changed-files: 90
          title: 'Code Coverage'
          update-comment: 'true'
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'


      - name: Code coverage report check
        if: ${{ steps.jacoco.outputs.coverage-changed-files < 90.0 || steps.jacoco.outputs.coverage-overall < 90.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Changed files coverage is less than expected, see reports for details')

      - name: Spotbugs
        id: spotbugs-check
        run: |
          set +e
          ./gradlew spotbugsMain spotbugsTest spotbugsIntegration --no-daemon
          echo "spotbugs_exit_code=$?" >> "$GITHUB_OUTPUT"
          set -e
        continue-on-error: true

      - name: Spotbugs report check
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/build/reports/spotbugs/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkstyle
        id: checkstyle-check
        run: |
          set +e
          ./gradlew checkstyleMain checkstyleTest checkstyleIntegration --no-daemon
          echo "checkstyle_exit_code=$?" >> "$GITHUB_OUTPUT"
          set -e
        continue-on-error: true

      - name: Checkstyle report check
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/build/reports/checkstyle/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: PMD
        id: pmd-check
        run: |
          set +e
          ./gradlew pmdMain pmdTest pmdIntegration --no-daemon
          echo "checkstyle_exit_code=$?" >> "$GITHUB_OUTPUT"
          set -e
        continue-on-error: true

      - name: PMD report check
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/build/reports/pmd/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate checks report
        if: steps.spotbugs-check.outputs.spotbugs_exit_code != '0' ||
          steps.checkstyle-check.outputs.checkstyle_exit_code != '0' ||
          steps.pmd-check.outputs.pmd_exit_code != '0'
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Quality checks failed, see reports for details')