name: ToDo App Build

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  pull-requests: write
  checks: write

jobs:
  build:
    name: Build and Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Compile
        run: ./gradlew assemble --no-daemon

      - name: Run unit tests
        run: ./gradlew test --no-daemon

      - name: Run integration tests
        run: ./gradlew integrationTest -x test --no-daemon

      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: build/reports/jacoco/test/jacocoTestReport.xml
          name: coverage-report
          verbose: true

      - name: Run checks
        id: run-checks-step
        run: |
          ./gradlew check --no-daemon
          find . -name "*.xml"
        continue-on-error: true

      - name: PMD report check
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/build/reports/pmd/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkstyle report check
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/build/reports/checkstyle/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Spotbugs report check
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/build/reports/spotbugs/**/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}