name: Pull Request Quality Gates

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  base-quality-gates:
    uses: ./.github/workflows/base-quality-gates.yml
    with:
      override-step: coverage-check

    steps:
      - name: Overall code coverage report check
        if: ${{ steps.jacoco.outputs.coverage-overall < 90.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Changed files coverage is less than expected, see reports for details')